version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_edutec
    environment:
      POSTGRES_DB: educacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: micaele12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_edutec
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:micaele12@db:5432/educacao

volumes:
  postgres_data:
